#!/bin/bash

SEL_ATTR='padrao'
FILTER_ATTR='descricao'
LAYER='pa_br_relevo_5000_2002_ibge'

for value in 'Tabuleiros Costeiros' 'Tabuleiro dos Rios Real/Vaza Barris' 'Serras do Leste Catarinense' 'Serras do Espinhaço/Tabatinga/Quadrilátero Ferrífero' 'Serras do Cachimbo/Sucunduri' 'Planícies Marinhas, Fluviomarinhas e/ou Fluviolacustres' 'Planícies Fluviais e/ou Fluviolacustres' 'Planaltos residuais dos Rios Tocantins/Araguaia' 'Planaltos e Serras dos Altos Rios Paraguai/Guaporé' 'Planaltos e Serras da Diamantina' 'Planaltos Residuais da Amazônia Setentrional' 'Planaltos Residuais da Amazônia Meridional' 'Planaltos Residuais Sertanejos' 'Planaltos Marginais ao Rio Amazonas' 'Planalto dos Parecis' 'Planalto dos Guimarães' 'Planalto dos Geraizinhos' 'Planalto do Alto Rio Grande' 'Planalto de Poços de Caldas' 'Planalto de Paranapiacaba' 'Planalto de Maracaju' 'Planalto das Araucárias' 'Planalto da Ibiapaba' 'Planalto da Canastra' 'Planalto da Campanha Gaúcha' 'Planalto da Caiapônia' 'Planalto da Borborena' 'Planalto Sul-Riograndense' 'Planalto Sertanejo' 'Planalto Centro-Sul Mineiro e Depressão de Belo Horizonte' 'Planalto Central da Bacia do Paraná' 'Planalto Central Brasileiro' 'Patamares dos Rios São Francisco/Tocantins e Serra da Saudade' 'Patamar Sertanejo' 'Patamar Oriental da Bacia do Paraná' 'Pantanal do Rio Guaporé' 'Pantanais Matogrossenses' 'Morros do Rio de Contas/Cristas e Colinas Pré-Litorâneas' 'Lençóis Maranhenses' 'Escarpas e Reversos do Planalto de Roraima' 'Escarpas e Reversos da Serra do Mar' 'Escarpas e Reversos da Serra da Mantiqueira' 'Depressão dos Rios Negro/Branco' 'Depressão dos Rios Javari-Contamana' 'Depressão dos Altos Rios Tocantins/Araguaia' 'Depressão dos Altos Rios Paraguai/Guaporé' 'Depressão do Solimões' 'Depressão do Rio Xingu' 'Depressão do Rio Paraíba do Sul' 'Depressão do Rio Jequitinhonha' 'Depressão do Rio Doce' 'Depressão do Rio Araguaia/Pantanal' 'Depressão do Médios Rios Tocantins/Araguaia' 'Depressão do Médio-Baixo Rio Amazonas' 'Depressão do Meio-Norte' 'Depressão do Baixo Rio Araguaia' 'Depressão do Alto-Médio Rio São Francisco e Baixadas dos Rios Jacaré/Salitre' 'Depressão de Boa Vista' 'Depressão da Amazônia Setentrional' 'Depressão da Amazônia Meridional' 'Depressão Periférico Paulista' 'Depressão Central Gaúcha' 'Depresssão Sertaneja e de Paranaguá' 'Cristas e Colinas do Rio Gurupi' 'Chapadas, Planaltos e Patamares dos Rios Jequitinhonha/Pardo' 'Chapadas dos Rios Irecê e Utinga' 'Chapadas do Rio São Francisco' 'Chapada dos Rios Tonã/Jatobá e Tabuleiros do Recôncavo/Tucano' 'Chapada dos Parecis' 'Chapada do Meio-Norte' 'Chapada do Araripe' 'Campos de Dunas do médio Rio São Francisco'      ; do
	echo $value
	ogrinfo -geom=FALSE -dialect sqlite -sql "SELECT $SEL_ATTR FROM $LAYER WHERE $FILTER_ATTR='$value' LIMIT 1" $LAYER.shp | grep -i $SEL_ATTR
done
